# Generated by Django 2.2.4 on 2019-12-31 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_tahun_ajaran_aktif'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tahun_ajaran_aktif',
            table='tabel_tahun_ajaran_aktif',
        ),
    ]
