# Generated by Django 2.2.4 on 2019-12-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_auto_20191231_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahun_ajaran',
            name='tahun',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
