# Generated by Django 2.2.4 on 2020-01-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_auto_20191231_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel_siswa',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
