# Generated by Django 2.2.4 on 2020-01-14 16:11

import adminpage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0006_auto_20200110_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel_siswa',
            name='foto',
            field=models.ImageField(upload_to=adminpage.models.images_directory_path),
        ),
        migrations.CreateModel(
            name='mata_pelajaran',
            fields=[
                ('kode_matpel', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpage.tahun_ajaran')),
            ],
            options={
                'db_table': 'tabel_mata_pelajaran',
            },
        ),
        migrations.CreateModel(
            name='kumpulan_soal',
            fields=[
                ('kode_soal', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('soal', models.TextField()),
                ('pilihan_1', models.CharField(max_length=255)),
                ('pilihan_2', models.CharField(max_length=255)),
                ('pilihan_3', models.CharField(max_length=255)),
                ('pilihan_4', models.CharField(max_length=255)),
                ('pilihan_5', models.CharField(max_length=255)),
                ('jawaban', models.CharField(max_length=255)),
                ('kode_matpel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpage.mata_pelajaran')),
            ],
            options={
                'db_table': 'tabel_kumpulan_soal',
            },
        ),
    ]
