# Generated by Django 2.2.4 on 2020-01-16 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_auto_20200114_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_pilih', models.CharField(max_length=255)),
                ('kode_soal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpage.kumpulan_soal')),
                ('nis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpage.tabel_siswa')),
            ],
            options={
                'db_table': 'tabel_save_jawaban',
            },
        ),
    ]
