# Generated by Django 2.2.4 on 2020-01-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0008_save_jawaban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel_siswa',
            name='nilai_indonesia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabel_siswa',
            name='nilai_inggris',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabel_siswa',
            name='nilai_mtk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
